#!/bin/bash
if [ $(xrandr | grep "HDMI1 connected" -c) -gt 0 ]; then
    xrandr --output HDMI1 --auto --right-of eDP1 &
    pactl set-card-profile 0 output:hdmi-stereo
else
    xrandr --output HDMI1 --off
    pactl set-card-profile 0 output:analog-stereo
fi

