#!/bin/bash
if [ "$1" == "+" ]; then
  pactl set-sink-volume 0 +5%
elif [ "$1" == "-" ]; then
  pactl set-sink-volume 0 -5%
elif [ "$1" == "." ]; then
  pactl set-sink-mute 0 toggle
fi
pkill -RTMIN+10 i3blocks
