#!/bin/bash
INTERFACE=1

if [ "$1" == "+" ]; then
  pactl set-sink-volume $INTERFACE +5%
elif [ "$1" == "-" ]; then
  pactl set-sink-volume $INTERFACE -5%
elif [ "$1" == "." ]; then
  pactl set-sink-mute $INTERFACE toggle
fi
pkill -RTMIN+10 i3blocks
